### ISSUE TITLE
Error on use tar class with equo command with python3.5

### ISSUE THREAD

**Issue by geaaru** [Sabayon/entropy#35]
For development I use currently python3.5 and I see that if I have this version when execute equo install command I receive this exception:
```
╠    ## Unpacking: app-office:libreoffice-5.2.5.1.259b8568ff6da2de17c77afb28e160715ef0dcf9~0.tbz2
Traceback (most recent call last):
  File "/usr/lib/entropy/lib/entropy/client/interfaces/package/actions/install.py", line 438, in _unpack_package
    catch_empty = True
  File "/usr/lib/entropy/lib/entropy/tools.py", line 2172, in uncompress_tarball
    _setup_file_metadata(tarinfo, epath)
  File "/usr/lib/entropy/lib/entropy/tools.py", line 2110, in _setup_file_metadata
    tar.chown(tarinfo, epath)
TypeError: chown() missing 1 required positional argument: 'numeric_owner'
☢    ## Unable to unpack package
☢    ## An error occurred while trying to unpack the package. Check if your system is healthy. Error: 1
```

I will try to see if there is a solution to this cross python version in the next weeks.

**Comment by geaaru** [comment]
I tried now with last python 3.5 and I can't reproduce this. Maybe is been fixed with a fresh minor release.
Can anyone confirm that works fine equo install with python3.5 so we can close this issue ?

**Comment by geaaru** [comment]
Unable to reproduce again this issue. I close it.
