### ISSUE TITLE
Python3.6 migration: utf-8 codec error on install app-misc/sabayon-skel

### ISSUE THREAD

**Issue by geaaru** [Sabayon/entropy#77]
```
╠  +++ >>>  (7/29) app-misc/sabayon-skel-17-r8
╠    ## Unpacking: app-misc:sabayon-skel-17-r8.0e2096c6a6a7e43b4cef93ff97aa67f28482e966~0.tbz2
╠    ## Installing package: app-misc/sabayon-skel-17-r8
╠    ## [Sabayon Linux skel tree]
☢ Hi. My name is Bug Reporter. I am sorry to inform you that the program crashed. Well, you know, shit happens.
☢ But there's something you could do to help me to be a better application.
☢ -- BUT, DO NOT SUBMIT THE SAME REPORT MORE THAN ONCE --
☢ Now I am showing you what happened. Don't panic, I'm here to help you.
Traceback (most recent call last):
  File "/usr/bin/equo", line 16, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/_entropy/solo/main.py", line 332, in main
    exit_st = func(*func_args)
  File "/usr/lib/python3.6/site-packages/_entropy/solo/commands/command.py", line 437, in _call_shared
    return func(client)
  File "/usr/lib/python3.6/site-packages/_entropy/solo/commands/upgrade.py", line 186, in _upgrade
    relaxed, multifetch)
  File "/usr/lib/python3.6/site-packages/_entropy/solo/commands/upgrade.py", line 250, in _upgrade_action
    package_matches=update)
  File "/usr/lib/python3.6/site-packages/_entropy/solo/commands/install.py", line 707, in _install_action
    exit_st = pkg.start()
  File "/usr/lib/python3.6/site-packages/entropy/client/interfaces/package/actions/action.py", line 218, in start
    exit_st = self._run()
  File "/usr/lib/python3.6/site-packages/entropy/client/interfaces/package/actions/install.py", line 260, in _run
    exit_st = method()
  File "/usr/lib/python3.6/site-packages/entropy/client/interfaces/package/actions/install.py", line 1410, in _install_phase
    return self._install_phase_unlocked(inst_repo)
  File "/usr/lib/python3.6/site-packages/entropy/client/interfaces/package/actions/install.py", line 1447, in _install_phase_unlocked
    inst_repo, remove_package_id)
  File "/usr/lib/python3.6/site-packages/entropy/client/interfaces/package/actions/install.py", line 1317, in _install_package_unlocked
    items_installed, items_not_installed)
  File "/usr/lib/python3.6/site-packages/entropy/client/interfaces/package/actions/install.py", line 2011, in _move_image_to_system_unlocked
    move_st = workout_file(currentdir, item)
  File "/usr/lib/python3.6/site-packages/entropy/client/interfaces/package/actions/install.py", line 1804, in workout_file
    protect, mask, protectskip, fromfile, tofile)
  File "/usr/lib/python3.6/site-packages/entropy/client/interfaces/package/actions/_manage.py", line 327, in _handle_config_protect
    protected = entropy.tools.istextfile(tofile)
  File "/usr/lib/python3.6/site-packages/entropy/tools.py", line 1929, in istextfile
    r = istext(f.read(blocksize))
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 0: invalid continuation byte

Frame decode in /usr/lib/python3.6/codecs.py at line 321
	                data = b'\xda\x1ameta\x01\x00\x00\x00\x00\x00v\x95~\x9c\x00\x00\x00$\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x004\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00'
	               final = False
	               input = b'\xda\x1ameta\x01\x00\x00\x00\x00\x00v\x95~\x9c\x00\x00\x00$\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x004\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00'
	                self = <encodings.utf_8.IncrementalDecoder object at 0xb1959d10>
```

**Comment by geaaru** [comment]
cc: @Enlik

**Comment by geaaru** [comment]
This happens in ARM. Not tested on amd64.
