### ISSUE TITLE
bugs with Python 3

### ISSUE THREAD

**Issue by Enlik** [Sabayon/entropy#80]
Before enabling Python 3 (in ebuild, after releasing Entropy with the changes related to sitedir), it's good to have a look at these.

*please add more if found*

1.

to reproduce:
```python
+        packages = entropy_client.Spm().search_paths_owners(["/bin/ls"])
```

```python
  File "./client/equo.py", line 16, in <module>
    main()
  File "/.../entropy/client/solo/main.py", line 332, in main
    exit_st = func(*func_args)
  File "/...entropy/client/solo/commands/command.py", line 437, in _call_shared
    return func(client)
  File "/.../entropy/client/solo/commands/libtest.py", line 112, in _test
    packages = entropy_client.Spm().search_paths_owners(["/bin/ls"])
  File "/.../entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 2105, in search_paths_owners
    slot = self.get_installed_package_metadata(pkg, "SLOT")
  File "/.../entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 759, in get_installed_package_metadata
    package, key, root = root)
  File "/.../entropy/lib/entropy/spm/plugins/interfaces/portage_plugin/__init__.py", line 775, in _get_installed_package_metadata
    return vartree.dbapi.aux_get(package, [key])[0]
  File "/usr/lib64/python3.6/site-packages/portage/dbapi/vartree.py", line 741, in aux_get
    mydir = self.getpath(mycpv)
  File "/usr/lib64/python3.6/site-packages/portage/dbapi/vartree.py", line 228, in getpath
    rValue = self._eroot + VDB_PATH + _os.sep + mykey
TypeError: must be str, not bytes
```

it's due to stdout of process being bytes and then:
```python
vartree.dbapi.aux_get(b'sys-apps/coreutils-8.30', ['SLOT'])
*** TypeError: must be str, not bytes
```

2.

"Dictionary size changed after iteration", I think it was in lib/entropy/server/interfaces/main.py:

```python
         if srv_dbcache is not None:
            for item in srv_dbcache.keys():
                 try:
                     srv_dbcache[item].close()
                 except ProgrammingError: # already closed?
                     pass
             srv_dbcache.clear()
```

packing with `list()` should help, something similar was done in 70bc63ebf9bd599861feaba312b71b4a99ff8c71 , but I propose to investigate further if it's really OK to do. It's somewhat complex why the dict. is actually mutated; from what I saw and recall, it's about closing all repositories which somehow lead into dict. modification (through `del sets_data[invalid_set]` in `_get_configured_package_sets`?).

It could be related to `srv_dbcache` keeping the same repo but without different settings (rw/ro etc.) as dict keys, especially `srv_dbcache`. It was however added long time ago during development, so… maybe it really works as intended and just needs a `list()`. A better or another look is needed.

3. 

```python
NameError: name 'file' is not defined
```

in matter and rigo_app, `type=file` in argparser.

4. (Old traceback, some lines could be outdated.)

```python
Traceback (most recent call last):
  File "./rigo/rigo_app.py", line 939, in _permissions_setup
    self._work_view_c.setup()
  File "/.../entropy/rigo/rigo/ui/gtk3/controllers/work.py", line 208, in setup
    box = self._setup_terminal_area()
  File "/.../entropy/rigo/rigo/ui/gtk3/controllers/work.py", line 104, in _setup_terminal_area
    _("<i>Show <b>Application Management</b> Progress</i>")))
TypeError: Must be string, not bytes
```

5. triggered by equo libtest

```python
  File "./client/equo.py", line 16, in <module>
    main()
  File "/.../entropy/client/solo/main.py", line 332, in main
    exit_st = func(*func_args)
  File "/.../entropy/client/solo/commands/command.py", line 437, in _call_shared
    return func(client)
  File "/.../entropy/client/solo/commands/libtest.py", line 129, in _test
    inst_repo, dump_results_to_file=dump, silent=quiet)
  File "/.../entropy/lib/entropy/qa.py", line 689, in test_shared_objects
    mywalk_iter = os.walk(etpConst['systemroot'] + ldpath)
TypeError: must be str, not bytes
```

6. lib/entropy/client/misc.py does this:
```python
if item[9] != "_"
```
(item is a byte array) which is never True (that's OKish) and silently so (that's not) because Python 3 (b'bla'[idx] is int). After fixing this, 7. occurs. Visible problem: eit commit does not warn about unmerged conf files.

To do: try to find all such occurences.

7. (Requires 6. being fixed).

eit commit:
```
 File "/root/t/entropy/lib/entropy/client/misc.py", line 251, in _load_maybe_add
    darkgreen(filepath),
  File "/root/t/entropy/lib/entropy/output.py", line 412, in darkgreen
    return colorize("darkgreen", text)
  File "/root/t/entropy/lib/entropy/output.py", line 286, in colorize
    return codes[color_key] + text + codes["reset"]
TypeError: must be str, not bytes
```

8. Also after correcting 6.

eit commit:

`diff: b'/etc/ufw/._cfg0000_user6.rules': Nie ma takiego pliku ani katalogu
diff: b'/etc/ufw/user6.rules': Nie ma takiego pliku ani katalogu`
(means ENOENT)

9. lib/entropy/services/client.py _encode_multipart_form and maybe others: concatenation of strings with bytes from "rb" files
@geaaru FYI

**Comment by Enlik** [comment]
update 1: (1) has a PR

1. (PR #82)

2.

"Dictionary size changed after iteration", I think it was in lib/entropy/server/interfaces/main.py:

```python
         if srv_dbcache is not None:
            for item in srv_dbcache.keys():
                 try:
                     srv_dbcache[item].close()
                 except ProgrammingError: # already closed?
                     pass
             srv_dbcache.clear()
```

packing with `list()` should help, something similar was done in 70bc63ebf9bd599861feaba312b71b4a99ff8c71 , but I propose to investigate further if it's really OK to do. It's somewhat complex why the dict. is actually mutated; from what I saw and recall, it's about closing all repositories which somehow lead into dict. modification (through `del sets_data[invalid_set]` in `_get_configured_package_sets`?).

It could be related to `srv_dbcache` keeping the same repo but without different settings (rw/ro etc.) as dict keys, especially `srv_dbcache`. It was however added long time ago during development, so… maybe it really works as intended and just needs a `list()`. A better or another look is needed.

3. 

```python
NameError: name 'file' is not defined
```

in matter and rigo_app, `type=file` in argparser.

4. (Old traceback, some lines could be outdated.)

```python
Traceback (most recent call last):
  File "./rigo/rigo_app.py", line 939, in _permissions_setup
    self._work_view_c.setup()
  File "/.../entropy/rigo/rigo/ui/gtk3/controllers/work.py", line 208, in setup
    box = self._setup_terminal_area()
  File "/.../entropy/rigo/rigo/ui/gtk3/controllers/work.py", line 104, in _setup_terminal_area
    _("<i>Show <b>Application Management</b> Progress</i>")))
TypeError: Must be string, not bytes
```

5. triggered by equo libtest

```python
  File "./client/equo.py", line 16, in <module>
    main()
  File "/.../entropy/client/solo/main.py", line 332, in main
    exit_st = func(*func_args)
  File "/.../entropy/client/solo/commands/command.py", line 437, in _call_shared
    return func(client)
  File "/.../entropy/client/solo/commands/libtest.py", line 129, in _test
    inst_repo, dump_results_to_file=dump, silent=quiet)
  File "/.../entropy/lib/entropy/qa.py", line 689, in test_shared_objects
    mywalk_iter = os.walk(etpConst['systemroot'] + ldpath)
TypeError: must be str, not bytes
```

@geaaru FYI

**Comment by Enlik** [comment]
All known crapage fixed. :)
