### ISSUE TITLE
equo: security oscheck explosion

### ISSUE THREAD

**Issue by geaaru** [Sabayon/entropy#81]
This happens inside a chroot executed from iso boot with command:

`equo sec oscheck -a --reinstall`

```
☢ Hi. My name is Bug Reporter. I am sorry to inform you that the program crashed. Well, you know, shit happens.
☢ But there's something you could do to help me to be a better application.
☢ -- BUT, DO NOT SUBMIT THE SAME REPORT MORE THAN ONCE --
☢ Now I am showing you what happened. Don't panic, I'm here to help you.
Traceback (most recent call last):
  File "/usr/bin/equo", line 18, in <module>
    main()
  File "/usr/lib/entropy/client/solo/main.py", line 332, in main
    exit_st = func(*func_args)
  File "/usr/lib/entropy/client/solo/commands/command.py", line 449, in _call_shared
    return func(client)
  File "/usr/lib/entropy/client/solo/commands/security.py", line 513, in _oscheck
    False, 1, [], package_matches=list(valid_matches))
  File "/usr/lib/entropy/client/solo/commands/install.py", line 578, in _install_action
    self._advise_packages_update(entropy_client)
  File "/usr/lib/entropy/client/solo/commands/_manage.py", line 690, in _advise_packages_update
    entropy_client.calculate_critical_updates()
  File "/usr/lib/entropy/lib/entropy/client/misc.py", line 38, in wrapped
    return method(self, *args, **kwargs)
  File "/usr/lib/entropy/lib/entropy/client/interfaces/dep.py", line 3029, in calculate_critical_updates
    self._settings_client_plugin.packages_configuration_hash(),
  File "/usr/lib/entropy/lib/entropy/client/interfaces/settings.py", line 566, in packages_configuration_hash
    repository_id, ",".join(sorted(packages)),
TypeError: sequence item 0: expected string, int found

Frame packages_configuration_hash in /usr/lib/entropy/lib/entropy/client/interfaces/settings.py at line 566
	       repository_id = u'sabayon-weekly_ids@@:of:sabayon-weekly'
	            packages = set([234450])
```

**Comment by geaaru** [comment]
I added some debug print (about `repository_id` and `packages` and this is what happens:

```
('REPOS ID ', u'sabayon-weekly')
('PACKAGES ', [u'www-servers/apache[threads]', u'<sys-kernel/linux-sabayon-4.19.8:4.19', u'<sys-kernel/sabayon-sources-4.19.8:4.19'])
('REPOS ID ', u'sabayon-weekly_ids@@:of:sabayon-weekly')
('PACKAGES ', set([234450]))

``

**Comment by geaaru** [comment]
@Enlik wdyt?

**Comment by Enlik** [comment]
Please show all files (for all repositories) such as:
```
/var/lib/entropy/client/database/amd64/sabayonlinux.org/standard/amd64/5/packages.db.mask
```

**Comment by Enlik** [comment]
That was ambiguous. I meant only `package.db.mask` files are needed (for all repositories).

**Comment by Enlik** [comment]
Closing for now.
